services:
  reviewmetricsprocessor:
    image: ${DOCKER_REGISTRY-}reviewmetricsprocessor
    build:
      context: .
      dockerfile: ReviewMetricsProcessor/Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    image: ${DOCKER_REGISTRY-}reviewmetricsprocessor.migrations
    build:
      context: .
      dockerfile: ReviewMetricsProcessor.Migrations/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrong@Passw0rd
      POSTGRES_DB: reviewmetrics
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
